### ISSUE TITLE
[UI] Adjust mobile css

### ISSUE THREAD

**Issue by clucasalcantara** [workwith-coffee/wwcoffee-frontend#18]
### Description

We need to think into items displacement and sentences length into a mobile layout, currently, the navigation is breaking and the placeholder for the search is too big for small screens.

### Preview
<img width="1680" alt="screenshot 2019-01-24 at 14 58 49 2" src="https://user-images.githubusercontent.com/6919712/51686723-ce911880-1fe8-11e9-9d01-20cff4b2c904.png">

**Comment by mvfsillva** [comment]
I close this issue because we should always think of mobile first!
